# Generated by Django 4.1.7 on 2023-02-16 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Camp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('camp_name', models.CharField(max_length=150)),
                ('about_camp', models.CharField(max_length=300)),
                ('image', models.ImageField(upload_to='Camp')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(max_length=250)),
                ('city', models.CharField(max_length=100)),
                ('area', models.CharField(max_length=100)),
                ('deadline', models.DateField()),
                ('begining', models.DateField()),
                ('image', models.ImageField(upload_to='Events')),
            ],
        ),
    ]
