# Generated by Django 4.1.7 on 2023-04-04 01:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='city',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='host',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='event',
            name='begining',
        ),
        migrations.RemoveField(
            model_name='event',
            name='deadline',
        ),
    ]
